export enum EComponentType {
  NONE = 'NONE',
  INPUT = 'INPUT',
  SELECT = 'SELECT',
  DATEPICKER = 'DATEPCIKER',
  ARRAY = 'ARRAY',
  INPUTNUMBER = 'INPUTNUMBER',
  NUMBERRADIUS = 'NUMBERRADIUS',
  RANGEPICKER = 'RANGEPICKER'
}
