export enum EComponentType {
  NONE = 'NONE',
  Input = 'Input',
  Select = 'Select',
  DatePicker = 'DatePicker',
  Array = 'Array',
  InputNumber = 'InputNumber',
  NumberAdius = 'NumberAdius',
  RangePicker = 'RangePicker',
  CompanySelect = 'CompanySelect',
  City = 'City',
  InboxOutlined = 'InboxOutlined',
  RoleSelect = 'RoleSelect',
  FieldSelect = 'FieldSelect',
  BankSelect = 'BankSelect',
  DelayRiskSelect = 'DelayRiskSelect',
  IdentitySelect = 'IdentitySelect',
  VehicleSelect = 'VehicleSelect',
  Upload = 'Upload',
  DepartmentSelect = 'DepartmentSelect',
  Password = 'Password'
}
